### ISSUE TITLE
[Bug] Fatal error

### ISSUE THREAD

**Issue by amadeu01** [LucianoPAlmeida/variable-injector#14] opened 2020-04-28 19:54 UTC
Try to run `variable-injector --file`, I got:

```
Fatal error: Error raised at top level: SwiftSyntax parser library isn't compatible: file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200
[1]    64575 illegal hardware instruction  variable-injector --file
```

**Comment by LucianoPAlmeida** [comment] 2020-04-28 19:57
Could you provide the version of Xcode/Toolchain and injector versions? Thanks

**Comment by amadeu01** [comment] 2020-04-28 21:16
@LucianoPAlmeida 

```
👉  xcodebuild -version
Xcode 11.4.1
Build version 11E503a
```

injector: 0.3.1

```
👉  swift --version
Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0
```

**Comment by LucianoPAlmeida** [comment] 2020-04-28 21:25
Can you try with 0.3.2, this relies on SwiftSyntax which can cause problems across versions of the language. Let us know if the problem is still there, and we will investigate :)

**Comment by amadeu01** [comment] 2020-04-28 21:50
I coudn't install the `0.3.2` version, but I managed to install the version on `master`
It worked.

**Comment by amadeu01** [comment] 2020-04-28 21:51
@LucianoPAlmeida the bitrise step uses the master version?

**Comment by LucianoPAlmeida** [comment] 2020-04-28 21:54
I remember we can specify the version there. What is the issue with 0.3.2? Maybe I can release a fix

**Comment by amadeu01** [comment] 2020-04-29 00:44
I couldn’t install the newest version due to the lack of the release, but you had fixed that ! Thanks @LucianoPAlmeida

**Comment by LucianoPAlmeida** [comment] 2020-04-29 00:53
Sure! Closing this then :)

**Closed as completed by LucianoPAlmeida** 2020-04-29 00:53 UTC
